# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [opened, deleted, trigger]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Display Payload
      run: |
        echo "Name of video: ${{ github.event.client_payload.name }}"
    - name: Install ImageMagick
      run: |
        cat /etc/ImageMagick-6/policy.xml | sed 's/none/read,write/g' | sudo tee /etc/ImageMagick-6/policy.xml

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install moviepy and pipenv
      run: |
        pip install moviepy
        pip install pipenv

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Execute script
      run: python main.py ${{ github.event.client_payload.name }}
      
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGEMAGICK_BINARY: ./magick
      
